name: MEP
on:
  workflow_dispatch:
    inputs:
      environnement:
        description: 'environnement dexecution'
        required: true
jobs:
  Premier-Job:
    name: Premier job
    runs-on : Ubuntu-latest
    steps:
      - name : estProd
        run : echo 'prod'
        if : ${{github.event.inputs.environnement == 'prod'}}
      - name : estQual
        run : echo 'qual'
        if : ${{github.event.inputs.environnement == 'qual'}}
      - name : estDev
        run : echo 'dev'
        if : ${{github.event.inputs.environnement == 'dev'}}
  
