name: MEP
on:
  workflow_dispatch:
    inputs:
      environnement:
        description: 'environnement dexecution'
        required: true
jobs:
  Premier-Job:
    name: Premier job
    runs-on : Ubuntu-latest
    steps:
      - name: testcondition
        run: echo 'prod'
        if : ${{github.event.inputs.environnement == 'prod'}}
  
